"""edit to statues

Revision ID: c68bcae7e4a4
Revises: 
Create Date: 2026-08-05 02:32:57.467108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c68bcae7e4a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               existing_nullable=True)

    with op.batch_alter_table('homevisits', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               existing_nullable=True)

    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               type_=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('homevisits', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               type_=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'DONE', 'NO_SHOW', name='status'),
               type_=mysql.ENUM('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
